name: CI Test
on:
  push:
    paths-ignore:
      - "src/**"
      - "__tests__/**"
  
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
      - "+([0-9])?(.{+([0-9]),x}).x"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set yarn version to 3
        run: yarn set version 3.2.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Runs tests
        run: yarn run test
