name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
      
      - name: Install dependencies
        run: npm ci

      - name: Runs tests
        run: npm run test
