name: Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - src/**
      - jest.config.js
      - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Runs tests
        run: yarn run test
