name: Yarn 3 Test
on:
  push:
    branches:
      - yarn3

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn
      
      - name: Set yarn version
        run: |
          yarn plugin import version
          yarn set version 3.2.0

      - name: Yarn version
        run: yarn --version

      - name: Yarn install
        run: yarn install --immutable --immutable-cache
      
      - name: Check diff
        run: git diff
